### ISSUE TITLE
Need usable peer bor (Mumbai testnet)

### ISSUE THREAD

**Issue by iltumio** [maticnetwork/launch#21]
It's impossible to sync bor on mumbai testnet since all the enodes found over the internet are not alive or have a broken state. Does anyone have a list of peers that can be used to sync bor on mumbai testnet?

**Comment by delroybosco** [comment]
Which documentation are you following to setup your Mumbai node

**Comment by iltumio** [comment]
I'm just following the instructions here inside the docker folder
https://github.com/maticnetwork/launch/blob/master/docker/README.md

**Comment by stephansmit** [comment]
Coincidentally, I have a similar issue. Managed to sync heimdall (on Mumbai), but now Bor has trouble finding peers.
I downloaded the snapshot from:  https://snapshots.matic.today/.
I am following this blogpost: https://chasewright.com/how-to-run-a-polygon-matic-mainnet-node/
While also incorporating the correct seeds and startup nodes as mentioned in this github repo.

```
version: '3.4'

services:
  bor:
    container_name: bor
    image: bor:latest
    build: /home/anonymous/Repositories/bor
    volumes:
      - /data/matic/mumbai/bor/:/root/.bor
    ports:
        - "10545:10545" # RPC
        - "31333:31333" # Peers (TCP)
        - "31333:31333/udp" # Peers (UDP)
    command:
        - bor
        - --syncmode=full
        - --networkid=137
        - --bor.heimdall=http://heimdallr:1317
        - --miner.gaslimit=200000000
        - --miner.gastarget=20000000
        - --datadir=/root/.bor/
        - --http
        - --port=31333
        - --http.addr=0.0.0.0
        - --http.port=10545
        - --http.api=eth,net,web3,admin,debug,bor
        - --http.corsdomain=*
        - --http.vhosts=*
        - --ws
        - --ws.addr=0.0.0.0
        - --ws.port=10545
        - --ws.api=eth,net,web3,admin,debug,bor
        - --ws.origins=*
        - --bootnodes=enode://095c4465fe509bd7107bbf421aea0d3ad4d4bfc3ff8f9fdc86f4f950892ae3bbc3e5c715343c4cf60c1c06e088e621d6f1b43ab9130ae56c2cacfd356a284ee4@18.213.200.99:30303
```
